build(deps): bump com.palantir.javaformat:gradle-palantir-java-format from 2.67.0 to 2.74.0 (#1994)
Bumps
[com.palantir.javaformat:gradle-palantir-java-format](https://github.com/palantir/palantir-java-format)
from 2.67.0 to 2.74.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/palantir/palantir-java-format/releases">com.palantir.javaformat:gradle-palantir-java-format's
releases</a>.</em></p>
<blockquote>
<h2>2.74.0</h2>
<h3>💡 Improvements</h3>
<ul>
<li>JEP 456: Unnamed Variables &amp; Patterns (<a
href="https://redirect.github.com/palantir/palantir-java-format/pull/1410">#1410</a>)</li>
</ul>
<h2>2.73.0</h2>
<h3>🐛 Fixes</h3>
<ul>
<li>bump spotless to version to <code>7.2.1</code> (<a
href="https://redirect.github.com/palantir/palantir-java-format/pull/1384">#1384</a>)</li>
</ul>
<h2>2.72.0</h2>
<h3>🐛 Fixes</h3>
<ul>
<li>Intellij uses the native image from
<code>.gradle/palantir-java-formatter-caches</code> (<a
href="https://redirect.github.com/palantir/palantir-java-format/pull/1306">#1306</a>)</li>
</ul>
<h2>2.71.0</h2>
<h3>🐛 Fixes</h3>
<ul>
<li>
<p>Fix the following error when running under JDK 25 EA:</p>
<pre><code>'java.util.Queue
com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()'
java.lang.NoSuchMethodError: 'java.util.Queue
com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()'
``` ([#1367](https://github.com/palantir/palantir-java-format/pull/1367))
<p></code></pre></p>
</li>
</ul>
<h2>2.70.0</h2>
<h3>🐛 Fixes</h3>
<ul>
<li>Update to use the new configuration cache safe <code>GradleOperatingSystem</code> (<a href="https://redirect.github.com/palantir/palantir-java-format/pull/1338">#1338</a>)</li>
</ul>
<h2>2.69.0</h2>
<h3>💡 Improvements</h3>
<ul>
<li>Make palantir-java-format support spotless 6.22.0, which is <a href="https://redirect.github.com/palantir/gradle-baseline/pull/3119">transitively brought in from baseline to support the configuration cache</a> (<a href="https://redirect.github.com/palantir/palantir-java-format/pull/1313">#1313</a>)</li>
</ul>
<h2>2.68.0</h2>
<h3>🐛 Fixes</h3>
<ul>
<li>bump <code>gradle-idea-configuration</code> and move off deprecated methods (<a href="https://redirect.github.com/palantir/palantir-java-format/pull/1298">#1298</a>)</li>
<li>Support for var in record patterns (<a href="https://redirect.github.com/palantir/palantir-java-format/pull/1312">#1312</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/palantir/palantir-java-format/commit/d36ea20f8f8c7924bf5e374a9327c83c6468e2b8"><code>d36ea20</code></a> Release 2.74.0</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/11e19e5bf20fbb3b46b2a97d3534e466eac60812"><code>11e19e5</code></a> JEP 456: Unnamed Variables &amp; Patterns (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1410">#1410</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/e0d0c59a2e91e42d49bd2bd592c95c6e76241a93"><code>e0d0c59</code></a> Excavator:  Update open-source publishing plugins (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1409">#1409</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/8a11f910950b2a2a139836c1c59e2b87e16e90eb"><code>8a11f91</code></a> Excavator:  Upgrades suppressible-error-prone to the latest version (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1407">#1407</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/46d4031ab24050804e101f8b04590045f55ec959"><code>46d4031</code></a> Excavator:  Upgrade failure-reports plugin (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1406">#1406</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/0493894ae04629443cc321ee069fc6330f97f1f8"><code>0493894</code></a> [High Priority] Excavator:  Upgrade gradle-consistent-versions dependency (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1">#1</a>...</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/86ff4af863df907ae6335a70659bd3e1304b6ea5"><code>86ff4af</code></a> Excavator:  Upgrades suppressible-error-prone to the latest version (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1401">#1401</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/ebb79b2bfa5513518d85879a5157a72475fd2073"><code>ebb79b2</code></a> Excavator:  Upgrades Baseline to the latest version (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1400">#1400</a>)</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/1be91b97a43730151c2cb9ce3c1c40152ded4544"><code>1be91b9</code></a> [High Priority] Excavator:  Upgrade gradle-consistent-versions dependency (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1">#1</a>...</li>
<li><a href="https://github.com/palantir/palantir-java-format/commit/0ccdff1c40d2986ca1091ab18c6099aa83e387b3"><code>0ccdff1</code></a> [High Priority] Excavator:  Upgrade buildscript dependencies (<a href="https://redirect.github.com/palantir/palantir-java-format/issues/1398">#1398</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/palantir/palantir-java-format/compare/2.67.0...2.74.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.palantir.javaformat:gradle-palantir-java-format&package-manager=gradle&previous-version=2.67.0&new-version=2.74.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>